language: python
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.40.1/hugo_0.40.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
script:
  - hugo # This commands builds your website on travis
# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master